### ISSUE TITLE
[Eclipse Deployment] Remove bins from deployed plugins

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eMoflon/emoflon-issue-tracking-system#315]
```
What steps will reproduce the problem?
1.  We do not need to pack /bin in our plugins anymore and this sometimes 
confuses Eclipse and should be avoided.
2.
3.

What is the expected output? What do you see instead?


Please use labels and text to provide additional information.


```

Original issue reported on code.google.com by `tonyAnjo...@googlemail.com` on 16 Jan 2015 at 10:21

**Comment by RolandKluge** [comment]
Does that mean that we should exclude "/bin" from bin.includes?

**Comment by anthonyanjorin** [comment]
I don't really know :(  All I notice when using our plugins is that the code is under plugin/src and also plugin/bin which is a bit irritating when you search for classes via ctrl+shift+T

This is a bit dangerous though - one has to be careful that everything still works after removing /bin.

**Comment by RolandKluge** [comment]
The problem seems to be caused by an ill-configured "bin.includes" in *build.properties*:
    output.. = bin/
    bin.includes = .,\
               bin/,\

The line with "output.." means that "." for "output" is "bin/". Using "." in "bin.includes" results in the topmost package (in our case *org*) to be placed in the root of the plugin. Using "bin/" in "bin.includes" results in the folder *bin/* being copied to the plugin as well.

Looking at some *org.apache* and *org.eclipse* plugins, I think that the desired behavior would be the first one.

Therefore, we should remove "bin/" from all our *build.properties* files.

**Comment by RolandKluge** [comment]
Was some work, but now it is done. I have removed "bin/" from *bin.includes* and checked that "output..=bin/" in every build.properties.
