### ISSUE TITLE
Duplicate Helpers : IntegrationSync and IntegrationTrafo

### ISSUE THREAD

**Issue by mballhausen** [eMoflon/emoflon-issue-tracking-system#361]
There are always to helper classes generated by eMoflon. An IntegrationSync and IntegrationTrafo. As the trafo just performs a Batch Transformation from my understanding there should be just one helper, the IntegrationSync. The reason for this is that the Sync class is also able to perfrom a Batch Transformation.

**Comment by anthonyanjorin** [comment]
Still not sure if we want to do this or not...

**Comment by erhanleblebici** [comment]
My personal opinion to this: the two helpers are necessary due to technical reasons. The idea is to perform a trafo and a synch afterwards without forcing the user write any Java code or configurations. If we provide one generic class, it is about writing some code/configuration rather than the push-the-button fashion.
