### ISSUE TITLE
[MOSL] Problem during tutorial

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-issue-tracking-system#517]
In Step 1 of Chapter 2 I should add the following code:

moveTo(floor : Floor) : void {
      if [moveFigure] {
           return
      }
}

This code is not accepted by the parser: "Mismatched token. Expected: IF, actual: CURLY_BRACKET_CLOSE"

The code that is inserted by "Click to perform" is different:

moveTo(floor : Floor) : void { 
		if [moveFigure]
		return
}

**Comment by anthonyanjorin** [comment]
@SchroedingersCatIsUndead shouldn't both versions actually work?  The brackets are redundant but should not be disallowed right?

**Comment by anthonyanjorin** [comment]
I have adjusted the code in the step to be exactly what is automatically inserted but this does not really fix this bug.

**Comment by SchroedingersCatIsUndead** [comment]
First for 

moveTo(floor : Floor) : void {
      if [moveFigure] {
           return
      }
}

I have forgotten to change this code. The reason for the problem is the restriction I added for Operations. The Restrictions defines that every operation must end with a return statement or with a condition where every path must be defined with the same restriction of a operation.

So correct versions are 
moveTo(floor : Floor) : void {
      if [moveFigure] {
           return
      } else {
           return
      }
}
 
or
moveTo(floor : Floor) : void {
      if [moveFigure] {
           return
      }
      return
}

or many more combinations.



Now for 
moveTo(floor : Floor) : void {
if [moveFigure]
return
}

This is short form for
moveTo(floor : Floor) : void {
  if [moveFigure]{}
  else {}
  return
}

In MOSL have missing { } - Brackets another meaning then in Programming Languages.
If you don't write them then MOSL thinks you don't want describe path. This is useful if you have something like this:

createAdmin() : Admin {
  if[adminExist]
  else {
    [createNewAdmin]
  }
return admin;
}
