### ISSUE TITLE
[MOSL] NACs have no effect

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-issue-tracking-system#521]
In Step 9, Chapter 2, the added NAC does not have any effect.

I used the "Click to perform" solution and can still move one figure above another (after purging .temp and SokobanLanguage.ecore)

**Comment by anthonyanjorin** [comment]
So I have checked and NACs are present but are not handled by Damocles.
This is because @SchroedingersCatIsUndead has used the new and more general way of representing NACs.  This should actually work according to @fdeckwerth , but I'm not sure if this is only on his branch or if it is still disabled in our main branch.

My suggestion:  

@SchroedingersCatIsUndead :  Please check how our old "simple" NACs are represented in the tree and use this for the time being.

@fdeckwerth / @gervarro  :  Please decide if advanced NACs are ready to be enabled.  If yes we need tests and documentation in our handbook.

Thanks,
Tony

**Comment by SchroedingersCatIsUndead** [comment]
now NAcs are build in the "old" way
